# Video-based training configuration
name: dvd_bluray_video
model_type: RecurrentMixPrecisionModel
num_gpu: 1
manual_seed: 1234

datasets:
  train:
    name: DVDBlurayVideo
    type: VideoRecurrentDataset
    dataroot_gt: datasets/dvd_bluray/gt  # Directory with GT video files
    dataroot_lq: datasets/dvd_bluray/lq  # Directory with LQ video files
    meta_info_file: datasets/dvd_bluray/video_metadata.json  # Metadata file created by prepare_dataset.py
    
    num_frame: 5
    gt_size: 256
    interval_list: [1]
    random_reverse: false
    use_hflip: true
    use_rot: true
    
    # loader
    num_worker_per_gpu: 4
    batch_size_per_gpu: 1
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

network_g:
  type: PSRT_sliding
  upscale: 4
  clip_size: 2
  img_size: [2, 64, 64]
  window_size: [2, 8, 8]
  img_range: 1.
  depths: [6, 6, 6, 6, 6, 6]
  embed_dim: 180
  num_heads: [6, 6, 6, 6, 6, 6]
  mlp_ratio: 2
  upsampler: 'pixelshuffle'
  resi_connection: '1conv'

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [150000, 250000, 350000, 450000]
    gamma: 0.5

  total_iter: 500000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: CharbonnierLoss
    loss_weight: 1.0
    eps: !!float 1e-9
    reduction: mean

  perceptual_opt:
    type: PerceptualLoss
    layer_weights:
      'conv3_4': 0.5
      'conv4_4': 1.0
      'conv5_4': 2.0
    vgg_type: vgg19
    use_input_norm: true
    range_norm: false
    perceptual_weight: 0.1
    style_weight: 0
    criterion: huber

# validation settings  
val:
  val_freq: !!float 2.5e3
  save_img: true

  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 0
      test_y_channel: true
      better: higher
    ssim:
      type: calculate_ssim
      crop_border: 0
      test_y_channel: true
      better: higher

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: 100  # Save frequently
  use_tb_logger: true
  wandb:
    project: srvideo-dvd-bluray
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500