# IART training configuration for DVD→Blu-ray restoration
# Fine-tuning from REDS BI N16 pretrained model

# general settings
name: IART_DVD_Bluray_5457frames
model_type: RecurrentMixPrecisionRTModel
scale: 4
num_gpu: 1
manual_seed: 0
find_unused_parameters: false
use_static_graph: true

# dataset and data loader settings
datasets:
  train:
    name: DVDBlurayDataset
    type: DVDRecurrentDataset
    dataroot_gt: /mnt/mercer/projects/srdata/dataset4x/train_gt
    dataroot_lq: /mnt/mercer/projects/srdata/dataset4x/train_lq
    meta_info_file: /mnt/mercer/projects/srdata/dataset4x/meta_info_train.txt
    val_partition: REDS4  # Use REDS4 partition (will be ignored for custom data)
    test_mode: False
    io_backend:
      type: disk

    num_frame: 16  # Number of frames per sequence
    gt_size: 256   # Patch size for training - 64x64 LQ after 4x downscale
    # For multi-scale training (optional):
    # patch_sizes: [256, 384, 512]  # Multiple patch sizes
    # patch_probs: [0.6, 0.3, 0.1]   # Probability of each size
    interval_list: [1]
    random_reverse: false
    use_hflip: false  # Disable flip to avoid dimension issues
    use_rot: false    # Disable rotation to avoid dimension issues

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 0  # Use 0 workers to simplify debugging
    batch_size_per_gpu: 1  # Batch size 1 to avoid dimension issues
    dataset_enlarge_ratio: 1  # Reduce for faster startup
    prefetch_mode: ~
    pin_memory: false  # Disable pinned memory

  # Validation disabled for initial training
  # val:
  #   name: DVDBlurayVal
  #   type: VideoRecurrentTestDataset
  #   dataroot_gt: /mnt/mercer/projects/srdata/dataset4x/train_gt
  #   dataroot_lq: /mnt/mercer/projects/srdata/dataset4x/train_lq
  #   
  #   cache_data: false
  #   io_backend:
  #     type: disk
  #   
  #   num_frame: -1

# network structures
network_g:
  type: IART
  mid_channels: 64
  embed_dim: 120
  depths: [6, 6, 6]
  num_heads: [6, 6, 6]
  window_size: [3, 8, 8]
  num_frames: 16  # Must match the pretrained model (N16)
  img_size: 64
  patch_size: 1
  cpu_cache_length: 100
  is_low_res_input: true
  spynet_path: experiments/pretrained_models/flownet/spynet_sintel_final-3d2a1287.pth

# path
path:
  pretrain_network_g: /mnt/mercer/projects/srdata/pretrained/IART_REDS_BI_N16.pth
  strict_load_g: true
  resume_state: ~

# training settings
train:

  # Gradient accumulation to simulate larger batch size
  gradient_accumulation_steps: 8

  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 2e-5  # Slightly higher LR with more data
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [50000]  # Longer period with more data
    restart_weights: [1]
    eta_min: !!float 1e-7

  total_iter: 50000  # More iterations with larger dataset
  use_grad_clip: true
  set_DINO_OOM: true
  half_precision: true  # Mixed precision training

  warmup_iter: 500  # Short warmup period

  # losses
  pixel_opt:
    type: CharbonnierLoss  # Standard Charbonnier loss (smooth L1)
    loss_weight: 1.0
    reduction: mean
  
  # FFT loss disabled for now
  # fft_opt:
  #   type: fftloss
  #   loss_weight: 0.1
    
  # Enable perceptual loss with more data
  perceptual_opt:
    type: PerceptualLoss
    layer_weights:
      'conv5_4': 1  
    vgg_type: vgg19
    use_input_norm: true
    range_norm: false
    perceptual_weight: 0.05  # Lower weight for fine-tuning
    style_weight: 0
    criterion: l1  # Use L1 instead of cb

# validation settings (disabled for now)
val:
  val_freq: !!float 999999  # Effectively disabled
  save_img: false
  grids: false
  max_minibatch: 8

  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    ssim:
      type: calculate_ssim  
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 10  # Print every 10 iterations to see progress sooner
  save_checkpoint_freq: !!float 100  # Save checkpoint every 100 iterations (more frequent for testing)
  use_tb_logger: true
  wandb:
    project: srvideo-dvd-bluray
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500